= TigerGraph CoPilot Release Notes
:experimental:
//:page-aliases: change-log.adoc, release-notes.adoc
:toc:
:toclevels:2

TigerGraph CoPilot 0.9 was released on Aug. 15, 2024.

TigerGraph CoPilot 0.5 (beta) was released on Apr. 29, 2024.

== New in CoPilot 0.9

** *Support for more LLM providers and models*: Ollama and HuggingFace.

** *Generates OpenCypher queries* if the preloaded queries aren't suitable to answer a question.

** *Chat history service* that stores conversation history and user feedback.

** *Context-aware conversation*, e.g. using conversation history to understand the context of follow-up questions.

** *Responses can include tables or small subgraphs* (experimental)

** *_Explain_ function* which reports the knowledge resources and reasoning that were applied to generate a response.

** *Chat UI* which incorporates the above features plus:
* Real-time updates on CoPilot's progress towards responding to your requests

* All these services have APIs, so developers can incorporate them into their own UI design.

** *Improved Docker Compose file* for easier deployment.

** *Refactored to a microservice architecture*
for greater flexibility, manageability, scalability, and performance.

** *Compatible with TigerGraph DB 3.9+*. Previously, SupportAI required TigerGraph 4.0.

== Key Features (Initial Release)

* xref:tg-copilot:intro:overview.adoc[TigerGraph CoPilot] -
** *Natural Language Inquiry*: The product’s natural-language and auto-execution capabilities empower non-technical users to focus on mining insights from their data through an AI assistant that they can “talk” to.

** *Graph-Augmented Generative AI*: TigerGraph CoPilot creates chat bots with augmented AI on a user’s own documents.

** *Reliable and Responsible AI*: TigerGraph CoPilot mitigates AI hallucination by allowing LLMs to access the graph database via curated queries.

** *High Scalability and Performance*: TigerGraph CoPilot runs graph analytics and obtains insights from a graph much faster than other LLM-graph solutions.

* xref:using-copilot:index.adoc[Using TigerGraph CoPilot] - TigerGraph CoPilot is now available in beta release to user to utilize in two ways:
** xref:tg-copilot:using-copilot:how2-use-on-cloud.adoc[On Cloud] - Via xref:tg-copilot:getstarted:oncloud.adoc[TigerGraph Cloud 4.0].
** xref:tg-copilot:using-copilot:how2-use-api.adoc[APIs] - Through a xref:tg-copilot:getstarted:self-managed.adoc[]



////
== Fixed issues
=== Fixed and Improved [v number]

==== Functionality
* Description (Ticket Number)

==== Crashes and Deadlocks

* Description (Ticket Number)

==== Improvements

* Description (Ticket Number)


== Known Issues and Limitations

[cols="4", separator=¦ ]
|===
¦ Description ¦ Found In ¦ Workaround ¦ Fixed In

|===

== Compatibility Issues

[cols="2", separator=¦ ]
|===
¦ Description ¦ Version Introduced

|===


== Deprecations

[cols="3", separator=¦ ]
|===
¦ Description ¦ Deprecated ¦ Removed

|===

== Release notes for previous versions
* TBD
////
